/// <reference types="node" />
import { afterEach, describe, expect, it } from "vitest";
import { spawnSync } from "node:child_process";
import { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import process from "node:process";

const root = fileURLToPath(new URL("../", import.meta.url));
const script = join(root, "scripts/version.mjs");
const files = ["package.json", "package-lock.json", "src-tauri/Cargo.toml", "src-tauri/Cargo.lock", "src-tauri/tauri.conf.json"];
const fixtures: string[] = [];
const initial = "0.1.0";

function write(root: string, file: string, text: string) {
  mkdirSync(dirname(join(root, file)), { recursive: true });
  writeFileSync(join(root, file), text);
}

function fixture(newline = "\n") {
  const directory = mkdtempSync(join(tmpdir(), "openleash-version-"));
  fixtures.push(directory);
  const contents: Record<string, string> = {
    "package.json": '{\n  "name": "openleash", "private": true,\n  "description": "escaped \\\"version\\\": \\\"9.9.9\\\"",\n  "version" : "0.1.0",\n  "dependencies": { "other": "0.1.0" },\n  "scripts": { "version": "node scripts/version.mjs --sync" }\n}\n',
    "package-lock.json": '{\n "name": "openleash",\n "version": "0.1.0",\n "lockfileVersion": 3,\n "packages": {\n  "node_modules/other": {"version": "0.1.0", "nested": [1, true, null, {"version": "0.1.0"}]},\n  "": {"name": "openleash", "version" : "0.1.0", "license": "MIT"}\n }\n}\n',
    "src-tauri/Cargo.toml": '# Keep this comment and spacing.\n[package] # app\nname = "openleash"\nversion  = \'0.1.0\' # keep the inline comment\n\n[dependencies]\nother = { version = "0.1.0", features = [] }\n\n[package.metadata.example]\nversion = "0.1.0"\n',
    "src-tauri/Cargo.lock": '# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = "before"\nversion = "0.1.0"\n\n[[package]] # app\nname = "openleash"\nversion = "0.1.0" # retain\ndependencies = [\n "before 0.1.0",\n "after",\n]\n\n[[package]]\nname = "after"\nversion = "0.1.0"\n',
    "src-tauri/tauri.conf.json": '{"version": "../package.json", "productName": "OpenLeash"}\n',
  };
  for (const [file, text] of Object.entries(contents)) write(directory, file, text.split("\n").join(newline));
  return directory;
}

function snapshot(directory: string) {
  return Object.fromEntries(files.map(file => [file, readFileSync(join(directory, file), "utf8")]));
}

function run(directory: string, ...args: string[]) {
  return spawnSync(process.execPath, [script, ...args], { cwd: directory, encoding: "utf8" });
}

function replace(directory: string, file: string, before: string, after: string) {
  write(directory, file, readFileSync(join(directory, file), "utf8").replace(before, after));
}

afterEach(() => {
  for (const directory of fixtures.splice(0)) rmSync(directory, { recursive: true, force: true });
});

describe("version metadata CLI", () => {
  it.each(["\n", "\r\n"])("updates only the app's exact version spans, preserving %j newlines", newline => {
    const directory = fixture(newline);
    const before = snapshot(directory);
    const version = "2.3.4-beta.2+build.007";
    const result = run(directory, version);
    expect(result.status, result.stderr).toBe(0);
    const after = snapshot(directory);
    expect(after["package.json"]).toBe(before["package.json"]!.replace('"version" : "0.1.0"', `"version" : "${version}"`));
    expect(after["package-lock.json"]).toBe(before["package-lock.json"]!
      .replace('"version": "0.1.0"', `"version": "${version}"`)
      .replace('"version" : "0.1.0"', `"version" : "${version}"`));
    expect(after["src-tauri/Cargo.toml"]).toBe(before["src-tauri/Cargo.toml"]!.replace("version  = '0.1.0'", `version  = '${version}'`));
    expect(after["src-tauri/Cargo.lock"]).toBe(before["src-tauri/Cargo.lock"]!.replace('name = "openleash"' + newline + 'version = "0.1.0"', 'name = "openleash"' + newline + `version = "${version}"`));
    expect(after["src-tauri/tauri.conf.json"]).toBe(before["src-tauri/tauri.conf.json"]);
    expect(run(directory, "--check", "--tag", `v${version}`).status).toBe(0);
  });

  it.each(["", "v1.2.3", "1.2", "1.2.3.4", "01.2.3", "1.02.3", "1.2.03", "1.2.3-01", "1.2.3-rc.01", "1.2.3-", "1.2.3+", "1.2.3+build..1", "1.2.3-beta_1", "1.2.3\n", " 1.2.3", "1.2.3 "])("rejects malformed version %j without writes", version => {
    const directory = fixture();
    const before = snapshot(directory);
    const result = run(directory, version);
    expect(result.status).toBe(1);
    expect(result.stderr).toContain("valid SemVer");
    expect(snapshot(directory)).toEqual(before);
  });

  it.each(["1.2.3-0", "1.2.3-0alpha.01a", "1.2.3-alpha-beta.9", "1.2.3+001"])("supports valid prerelease and build identifiers %s", version => {
    const directory = fixture();
    const result = run(directory, version);
    expect(result.status, result.stderr).toBe(0);
    expect(run(directory, "--check").status).toBe(0);
  });

  it.each([[], ["--tag", "v0.1.0"], ["--sync", "0.2.0"], ["0.2.0", "--check"], ["--check", "--tag"], ["--check", "--tag", "v0.1.0", "extra"]].map(args => ({ args })))("rejects ambiguous or missing arguments $args without writes", ({ args }) => {
    const directory = fixture();
    const before = snapshot(directory);
    expect(run(directory, ...args).status).toBe(1);
    expect(snapshot(directory)).toEqual(before);
  });

  it("checks alignment read-only and reports drift in every mirrored version", () => {
    const directory = fixture();
    const before = snapshot(directory);
    expect(run(directory, "--check").status).toBe(0);
    expect(snapshot(directory)).toEqual(before);
    const changes = [
      ["package-lock.json", '"version": "0.1.0"'],
      ["package-lock.json", '"version" : "0.1.0"'],
      ["src-tauri/Cargo.toml", "version  = '0.1.0'"],
      ["src-tauri/Cargo.lock", 'name = "openleash"\nversion = "0.1.0"'],
    ];
    for (const [file, text] of changes) {
      write(directory, file!, before[file!]!);
      replace(directory, file!, text!, text!.replace(initial, "0.2.0"));
      const drifted = snapshot(directory);
      const result = run(directory, "--check");
      expect(result.status).toBe(1);
      expect(result.stderr).toContain("Version drift");
      expect(result.stderr).toContain(file);
      expect(snapshot(directory)).toEqual(drifted);
      write(directory, file!, before[file!]!);
    }
  });

  it.each(["v0.2.0", "0.1.0", "v01.1.0"])("rejects release tag %s without writes", tag => {
    const directory = fixture();
    const before = snapshot(directory);
    expect(run(directory, "--check", "--tag", tag).status).toBe(1);
    expect(snapshot(directory)).toEqual(before);
  });

  it.each([
    ["src-tauri/tauri.conf.json", '{"version": "0.1.0"}'],
    ["package-lock.json", '{"version": "0.1.0", "packages": {}}'],
    ["package-lock.json", '{"version": "0.1.0", "version": "0.1.0"}'],
    ["package-lock.json", '{"version": "bad", "packages": {"": {"version": "0.1.0"}}}'],
    ["src-tauri/Cargo.toml", '[package]\nname = "openleash"\nversion = "bad"\n'],
    ["src-tauri/Cargo.lock", '[[package]]\nname = "other"\nversion = "0.1.0"\n'],
    ["src-tauri/Cargo.lock", '[[package]]\nname = "openleash"\nversion = "0.1.0"\nversion = "0.1.0"\n'],
    ["src-tauri/Cargo.lock", '[[package]]\nname = "openleash"\nversion = "0.1.0"\n[[package]]\nname = "openleash"\nversion = "0.1.0"\n'],
    ["src-tauri/tauri.conf.json", '{ malformed json'],
  ])("validates malformed metadata in %s before writing any file", (file, text) => {
    const directory = fixture();
    write(directory, file, text);
    const before = snapshot(directory);
    const result = run(directory, "0.2.0");
    expect(result.status).toBe(1);
    expect(snapshot(directory)).toEqual(before);
  });

  it("syncs npm's already-bumped manifests into Cargo without another bump", () => {
    const directory = fixture();
    const version = "0.2.0-rc.1";
    // npm version updates package.json and package-lock.json before running its
    // `version` lifecycle; Cargo still contains the previous version at this point.
    for (const file of ["package.json", "package-lock.json"]) {
      const text = readFileSync(join(directory, file), "utf8");
      const json = JSON.parse(text);
      json.version = version;
      if (file === "package-lock.json") json.packages[""].version = version;
      write(directory, file, JSON.stringify(json, null, 2) + "\n");
    }
    const before = snapshot(directory);
    const result = run(directory, "--sync");
    expect(result.status, result.stderr).toBe(0);
    const after = snapshot(directory);
    expect(after["package.json"]).toBe(before["package.json"]);
    expect(after["package-lock.json"]).toBe(before["package-lock.json"]);
    expect(after["src-tauri/Cargo.toml"]).toContain(`version  = '${version}'`);
    expect(after["src-tauri/Cargo.lock"]).toContain(`version = "${version}"`);
    expect(run(directory, "--check").status).toBe(0);
    expect(run(directory, "--sync").stdout).toContain("0 files changed");
    expect(snapshot(directory)).toEqual(after);
  });

  it("runs npm version patch --no-git-tag-version and its sync lifecycle in a temporary project", () => {
    const npm = process.env.npm_execpath;
    expect(npm, "Run this suite through npm test so npm's CLI path is available").toBeTruthy();
    const directory = fixture();
    write(directory, "scripts/version.mjs", readFileSync(script, "utf8"));
    const result = spawnSync(process.execPath, [npm!, "version", "patch", "--no-git-tag-version", "--offline", "--no-audit", "--no-fund"], {
      cwd: directory,
      encoding: "utf8",
      env: { ...process.env, npm_config_cache: join(directory, ".npm-cache"), npm_config_userconfig: join(directory, ".npmrc"), npm_config_update_notifier: "false" },
    });
    expect(result.status, result.stderr).toBe(0);
    expect(JSON.parse(readFileSync(join(directory, "package.json"), "utf8")).version).toBe("0.1.1");
    expect(run(directory, "--check", "--tag", "v0.1.1").status).toBe(0);
  });
});

it("keeps the repository's release metadata aligned with package.json", () => {
  const result = run(root, "--check");
  expect(result.status, result.stderr).toBe(0);
});
